baseurl = "https://kind-almeida-7bb21b.netlify.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3

